use std::{
  ffi::{OsStr, OsString},
  path::{Path, PathBuf},
};

use tauri_plugin_shell::ShellExt;

use chrono::Utc;

use crate::api::models::Cookie;

pub fn write_netscape_cookie_file(path: &Path, cookies: &[Cookie]) -> anyhow::Result<()> {
  if let Some(parent) = path.parent() {
    std::fs::create_dir_all(parent).ok();
  }
  let mut out = String::new();
  out.push_str("# Netscape HTTP Cookie File\n");
  out.push_str("# This file was generated by UtubeHolic (Tauri/Rust)\n\n");

  for c in cookies {
    let domain = c.domain.clone().unwrap_or_default();
    let name = c.name.clone().unwrap_or_default();
    let value = c.value.clone().unwrap_or_default();
    if domain.is_empty() || name.is_empty() {
      continue;
    }
    let path_ = c.path.clone().unwrap_or_else(|| "/".to_string());
    let include_subdomains = if domain.starts_with('.') { "TRUE" } else { "FALSE" };
    let secure = if c.secure.unwrap_or(false) { "TRUE" } else { "FALSE" };
    let expires = c
      .expiration_date
      .map(|v| v as i64)
      // Session cookies passed from Chrome/Edge extensions often have an empty expirationDate.
      // Since expires=0 in Netscape format is interpreted as ‘1970-01-01’ and may be treated as immediately expired,
      // the default value is set to ‘sufficiently far in the future’.
      .unwrap_or_else(|| Utc::now().timestamp() + 60 * 60 * 24 * 365);

    out.push_str(&format!(
      "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
      domain,
      include_subdomains,
      path_,
      secure,
      expires,
      name,
      value
    ));
  }

  std::fs::write(path, out)?;
  Ok(())
}

pub async fn cleanup_cookie_file(path: &Path) {
  let path = path.to_path_buf();
  let _ = tokio::task::spawn_blocking(move || {
    if path.exists() {
      std::fs::remove_file(&path).ok();
    }
  })
  .await;
}

pub fn list_files_by_video_id(dir: &Path, video_id: &str) -> Vec<PathBuf> {
  // yt-dlp saves Twitter files with the raw number ID, so we strip the 'twitter:' prefix
  let search_id = video_id.strip_prefix("twitter:").unwrap_or(video_id);

  let mut out = Vec::new();
  let Ok(rd) = std::fs::read_dir(dir) else {
    return out;
  };
  for ent in rd.flatten() {
    let p = ent.path();
    if !p.is_file() {
      continue;
    }
    let name = p.file_name().and_then(|s| s.to_str()).unwrap_or("");
    if name.contains(search_id) {
      out.push(p);
    }
  }
  out
}

pub fn delete_files(paths: &[PathBuf]) -> Vec<String> {
  let mut deleted = Vec::new();
  for p in paths {
    if std::fs::remove_file(p).is_ok() {
      deleted.push(p.to_string_lossy().to_string());
    }
  }
  deleted
}

pub fn resolve_sidecar_program(app: &tauri::AppHandle, name: &str) -> anyhow::Result<PathBuf> {
  let cmd = app.shell().sidecar(name)?;
  let std_cmd: std::process::Command = cmd.into();
  let p: &OsStr = std_cmd.get_program();
  Ok(PathBuf::from(OsString::from(p)))
}
